;************** PROVA 2 DE ARQUITETURA DE COMPUTADORES 2, GUSTAVO LOPES RODRIGUES*****************
LIST   P=PIC16F628A
RADIX DEC	
#INCLUDE <P16F628A.INC>
	__CONFIG H'3F10'

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE
					;USUÁRIO
					;VARIAVEIS DE CONTADOR USADA
	CONTADOR1		
	CONTADOR2
	CONTADOR3
	CONTADOR4
	CONTADOR5
	ENDC			;FIM DO BLOCO DE MEMÓRIA		
	
	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
		
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0
	CLRF TRISB
	BCF STATUS, RP0

REPETE
	
	CALL ATRASO       ; FUNCAO DE ATRASO = 22.655264 secs ( dia 22 + matricula 655264 = 22.655264)
	GOTO REPETE


ATRASO				
	MOVLW	200
	MOVWF	CONTADOR1	; contador1=200
	MOVLW	43
	MOVWF	CONTADOR2	; contador2=43
	MOVLW	87
	MOVWF	CONTADOR3	; contador3=87
	MOVLW	10
	MOVWF	CONTADOR4	; contador4=10
	MOVLW	94
	MOVWF	CONTADOR5	; contador5=94
ATRASO1			
	CLRF CONTADOR1
ATRASO2	
	NOP
	DECFSZ	CONTADOR1	
	GOTO	ATRASO2	 
	NOP				
	DECFSZ	CONTADOR2	
	GOTO	ATRASO2
	NOP
	DECFSZ	CONTADOR3	
	GOTO	ATRASO1
	
ATRASO3
	DECFSZ	CONTADOR4	
	GOTO	ATRASO3	 
ATRASO4
	DECFSZ	CONTADOR5	
	GOTO	ATRASO4
	RETURN
	


END